In [93]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [94]:
# 1. How many negative numbers are there?

neg_num = a[a<0]
print(len(neg_num))

4


In [95]:
# 2. How many positive numbers are there?

pos_num = a[a>0]
print(len(pos_num))

5


In [96]:
# 3. How many even positive numbers are there?

pos_even_num = a[np.where(a>0) and (a % 2 == 0)]
print(len(pos_even_num))

8


In [97]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?

plus_three = a + 3
pos_num_plus_three = plus_three[plus_three>0]
print(len(pos_num_plus_three))

10


In [98]:
# 5. If you squared each number, what would the new mean and standard deviation be?

squared = a**2
print(squared.mean())
print(squared.std())

74.0
144.0243035046516


In [102]:
# 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

b = a - a.mean()
print(b.mean())

0.0


In [100]:
# 7. Calculate the z-score for each data point. 
# Recall that the z-score is given by:

z_score = (a - a.mean()) / a.std()
print(z_score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [26]:
# 8. Copy the setup and exercise directions from More Numpy Practice 
# into your numpy_exercises.py and add your solutions.
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of 
# all the numbers in above list
sum_of_a = sum(a)
print(sum_of_a)

55


In [35]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of 
# all the numbers in the above list
min_of_a = min(a)
print(min_of_a)

1


In [36]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of 
# all the numbers in the above list
max_of_a = max(a)
print(max_of_a)

10


In [37]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of 
# all the numbers in the above list
mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [42]:
# Exercise 5 - Make a variable named product_of_a to hold the product 
# of multiplying all the numbers in the above list together
product_of_a = 1
for x in a:
    product_of_a = product_of_a * x
print(product_of_a)

3628800


In [43]:
# Exercise 6 - Make a variable named squares_of_a. 
# It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for x in a:
    squares_of_a.append(x**2)
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [44]:
# Exercise 7 - Make a variable named odds_in_a. 
# It should hold only the odd numbers
odds_in_a = []
for x in a:
    if x %2 != 0:
        odds_in_a.append(x)
print(odds_in_a)

[1, 3, 5, 7, 9]


In [45]:
# Exercise 8 - Make a variable named evens_in_a. 
# It should hold only the evens.
evens_in_a = []
for x in a:
    if x %2 == 0:
        evens_in_a.append(x)
print(evens_in_a)

[2, 4, 6, 8, 10]


In [46]:
## What about life in two dimensions? 
# A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, 
# average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [50]:
# Exercise 1 - refactor the following to use numpy. 
# Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable 
# is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
# print(sum_of_b)

b = np.array(b)
sum_of_b = b.sum()
print(sum_of_b)

33
33


In [52]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

min_of_b = b.min()
print(min_of_b)

3


In [53]:
# Exercise 3 - refactor the following maximum calculation to find 
# the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
print(max_of_b)

8


In [54]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()
print(mean_of_b)

5.5


In [55]:
# Exercise 5 - refactor the following to use numpy for calculating the 
# product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number
product_of_b = b.prod()
print(product_of_b)

20160


In [56]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = b**2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


In [57]:
# # Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

odds_in_b = b[b % 2 != 0]
print(odds_in_b)

[3 5 7]


In [58]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


In [59]:
# Exercise 9 - print out the shape of the array b
print(b.shape)

(2, 3)


In [60]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [61]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [62]:
# Exercise 12 - reshape the array b to be a list of 6 lists, 
# each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [63]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [65]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)

print('min:', c.min())
print('max:', c.max())
print('sum:', c.sum())
print('product:', c.prod())

min: 1
max: 9
sum: 45
product: 362880


In [66]:
# Exercise 2 - Determine the standard deviation of c.

print('std:', c.std())

std: 2.581988897471611


In [67]:
# Exercise 3 - Determine the variance of c.
print('variance: ', c.var())

variance:  6.666666666666667


In [68]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)

(3, 3)


In [69]:
# Exercise 5 - Transpose c and print out transposed result.
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [70]:
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [71]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print((c * np.transpose(c)).sum())

261


In [72]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
print((c * np.transpose(c)).prod())

131681894400


In [73]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [75]:
# Exercise 1 - Find the sine of all the numbers in d
d = np.array(d)
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [76]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [77]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(c)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [78]:
# Exercise 4 - Find all the negative numbers in d
print(d[d < 0])

[-90 -30 -45 -45]


In [79]:
# Exercise 5 - Find all the positive numbers in d
print(d[d>0])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [80]:
# Exercise 6 - Return an array of only the unique numbers in d.
print(np.unique(d))

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [82]:
# Exercise 7 - Determine how many unique numbers there are in d.
print(len(np.unique(d)))

11


In [83]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [84]:
# Exercise 9 - Transpose and then print out the shape of d.
print(np.transpose(d))

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [85]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])